---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    headers:
      Cookie: 'oraclelicense=accept-securebackup-cookie'
    dest: "/tmp/{{ file }}"

- name: install /tmp/{{ file }}
  become: yes
  yum:
    name: "/tmp/{{ file }}"
    state: present

- name: set JAVA_HOME=/usr/java/latest
  become: yes
  lineinfile:
    dest: /etc/profile.d/java.sh
    create: yes
    state: present
    regexp: '^export JAVA_HOME'
    line: 'export JAVA_HOME=/usr/java/latest'
