---

- name: install 'python-pip', 'python-devel'
  become: yes
  yum:
    update_cache: yes
    name: ['python-pip', 'python-devel']
    state: installed
    enablerepo: "epel"

- name: install diamond
  become: yes
  pip:
    name: diamond
    version: 4.0.515
  notify: "restart diamond"

- name: create diamond directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/diamond
    - /var/log/diamond
  notify: "restart diamond"

- name: configure /etc/diamond/diamond.conf
  become: yes
  template:
    src: templates/diamond.conf.j2
    dest: /etc/diamond/diamond.conf
  notify: "restart diamond"

- name: install diamond systemd unit file
  become: yes
  template:
    src: templates/diamond.service.j2
    dest: "{{ system_units }}/diamond.service"
  notify: "restart diamond"

- name: run handlers
  meta: flush_handlers
