---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"

- name: extract {{ download }}/{{ file }}
  become: yes
  unarchive:
    src: "{{ download }}/{{ file }}"
    dest: "{{ usr_local }}"
    copy: no
    creates: "{{ zookeeper_home }}"
    owner: root
    group: root
  notify: "restart zookeeper"

- name: set PATH=$PATH:{{ zookeeper_home }}/bin
  become: yes
  lineinfile:
    dest: "{{ etc_profiles }}/zookeeper.sh"
    create: yes
    state: present
    regexp: '^PATH'
    line: 'PATH=$PATH:{{ zookeeper_home }}/bin'

- name: copy zoo.cfg to {{ zookeeper_home }}/conf/zoo.cfg
  become: yes
  template:
    src: templates/zoo.cfg.j2
    dest: "{{ zookeeper_home }}/conf/zoo.cfg"
  notify: "restart zookeeper"

- name: copy jaas.conf to {{ zookeeper_home }}/conf/jaas.conf
  become: yes
  template:
    src: templates/jaas.conf.j2
    dest: "{{ zookeeper_home }}/conf/jaas.conf"
  register: jaas_conf

- name: create {{ zookeeper_data_dir }}
  become: yes
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
  notify: "restart zookeeper"

- name: create {{ zookeeper_log_dir }}
  become: yes
  file:
    path: "{{ zookeeper_log_dir }}"
    state: directory
  notify: "restart zookeeper"

- name: create myid in {{ zookeeper_data_dir }} for {{ groups.zookeeper.index(inventory_hostname) + 1 }}
  become: yes
  copy:
    content: "{{ groups.zookeeper.index(inventory_hostname) + 1 }}"
    dest: "{{ zookeeper_data_dir }}/myid"
    force: yes
  notify: "restart zookeeper"

- name: copy jmxtrans-agent.xml {{ jmxtrans_dest }}/{{ jmxagent }}
  become: yes
  template:
    src: templates/jmxtrans-agent.xml.j2
    dest: "{{ jmxtrans_dest }}/{{ jmxagent }}"
  notify: "restart zookeeper"

- name: copy zookeeper.environment {{ zookeeper_home }}/zookeeper.environment
  become: yes
  template:
    src: templates/zookeeper.environment.j2
    dest: "{{ zookeeper_home }}/zookeeper.environment"
  notify: "restart zookeeper"

- name: install zookeeper systemd unit file
  become: yes
  template:
    src: templates/zookeeper.service.j2
    dest: "{{ system_units }}/zookeeper.service"
  notify: "restart zookeeper"

- name: run handlers
  meta: flush_handlers
