---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"

- name: extract {{ download }}/{{ file }}
  become: yes
  unarchive:
    src: "{{ download }}/{{ file }}"
    dest: "{{ usr_local }}"
    copy: no
    creates: "{{ zookeeper_home }}"

- name: set ownership on {{ zookeeper_home }}
  become: yes
  file:
    path: "{{ zookeeper_home }}"
    owner: vagrant
    group: vagrant
    recurse: yes
    mode: 0755

- name: set PATH=$PATH:{{ zookeeper_home }}/bin
  become: yes
  lineinfile:
    dest: "{{ etc_profiles }}/zookeeper.sh"
    create: yes
    state: present
    regexp: '^PATH'
    line: 'PATH=$PATH:{{ zookeeper_home }}/bin'

- name: copy zoo.cfg to {{ zookeeper_home }}/conf/zoo.cfg
  template:
    src: templates/zoo.cfg.j2
    dest: "{{ zookeeper_home }}/conf/zoo.cfg"
  register: zoo_config

- name: copy jaas.conf to {{ zookeeper_home }}/conf/jaas.conf
  template:
    src: templates/jaas.conf.j2
    dest: "{{ zookeeper_home }}/conf/jaas.conf"
  register: jaas_conf

- name: create {{ zookeeper_data_dir }}
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory

- name: create {{ zookeeper_log_dir }}
  file:
    path: "{{ zookeeper_log_dir }}"
    state: directory

- name: create myid in {{ zookeeper_data_dir }} for {{ groups.zookeeper.index(inventory_hostname) + 1 }}
  copy:
    content: "{{ groups.zookeeper.index(inventory_hostname) + 1 }}"
    dest: "{{ zookeeper_data_dir }}/myid"
    force: yes

- name: copy jmxtrans-agent.xml {{ jmxtrans_dest }}/{{ jmxagent }}
  become: yes
  template:
    src: templates/jmxtrans-agent.xml.j2
    dest: "{{ jmxtrans_dest }}/{{ jmxagent }}"
  register: zoo_config_jmx

- name: copy zookeeper.environment {{ zookeeper_home }}/zookeeper.environment
  become: yes
  template:
    src: templates/zookeeper.environment.j2
    dest: "{{ zookeeper_home }}/zookeeper.environment"
  register: zookeeper_env

- name: install zookeeper systemd unit file
  become: yes
  template:
    src: templates/zookeeper.service.j2
    dest: "{{ system_units }}/zookeeper.service"
  register: zoo_service

- name: restart zookeeper
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: zookeeper
    daemon_reload: yes
  when: zoo_service.changed or zoo_config.changed or zoo_config_jmx.changed or zookeeper_env.changed or jaas_conf.changed

- name: wait until zookeeper has started
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 2181
