---

- import_role:
    name: elastic

- name: install filebeat
  become: yes
  yum:
    name: filebeat-{{ version }}
    state: present
    update_cache: yes
  notify: restart filebeat

- name: copy filebeat.yml /etc/filebeat/filebeat.yml
  become: yes
  template:
    src: templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat

- name: create /etc/filebeat/configs
  become: yes
  become_method: sudo
  file:
    path: /etc/filebeat/configs
    state: directory
    mode: 0755

- meta: flush_handlers

- name: setup filebeat
  become: yes
  shell: filebeat setup -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["{{ groups['elk'][0] }}:9200"]' -E 'setup.kibana.host={{ groups['elk'][0] }}:5601' && touch /tmp/filebeat.setup
  args:
    creates: /tmp/filebeat.setup
