---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: "{{ download }}/{{ file }}"

- name: create directory {{ jmxtrans_dest }}
  become: yes
  file:
    path: "{{ jmxtrans_dest }}"
    state: directory
    mode: 0755

- name: download {{ jmx_trans }}
  become: yes
  get_url:
    url: "{{ jmx_trans }}"
    dest: "{{ jmxtrans_dest }}/jmxtrans-agent.jar"

- name: install {{ download }}/{{ file }}
  become: yes
  yum:
    name: "{{ download }}/{{ file }}"
    state: present

- name: set JAVA_HOME=/usr/java/latest
  become: yes
  lineinfile:
    dest: "{{ etc_profiles }}/java.sh"
    create: yes
    state: present
    regexp: '^export JAVA_HOME'
    line: 'export JAVA_HOME=/usr/java/latest'
