---

- name: install graphite-web, python-carbon and python-pip
  become: yes
  yum:
    name: ['graphite-web', 'python-carbon', 'python-pip']
    update_cache: true
    state: installed
    enablerepo: "epel"
  notify: "restart graphite"

- name: install django==1.4
  become: yes
  pip:
    name:
      - django==1.4

- name: copy /etc/httpd/conf.d/graphite-web.conf
  become: yes
  template:
    src: templates/graphite-web.conf.j2
    dest: /etc/httpd/conf.d/graphite-web.conf
  notify: "restart graphite"

- name: graphite syncdb
  become: yes
  command: /usr/lib/python2.7/site-packages/graphite/manage.py syncdb --noinput
  args:
    creates: /var/lib/graphite-web/graphite.db
  notify: "restart graphite"

- name: set /var/lib/graphite-web apache:apache
  become: yes
  file:
    path: /var/lib/graphite-web
    owner: apache
    group: apache
    recurse: yes
  notify: "restart graphite"

- name: run handlers
  meta: flush_handlers
