---

- name: install epel repo
  become: yes
  yum:
    name: "{{ item }}"
    update_cache: true
    state: installed
  with_items:
    - http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm

- name: install graphite and carbon
  become: yes
  yum:
    name: "{{ item }}"
    update_cache: true
    state: installed
    enablerepo: "epel"
  with_items:
    - graphite-web
    - python-carbon
  notify: "restart graphite"

- name: copy /etc/httpd/conf.d/graphite-web.conf
  become: yes
  template:
    src: templates/graphite-web.conf.j2
    dest: /etc/httpd/conf.d/graphite-web.conf
  notify: "restart graphite"

- name: graphite syncdb
  become: yes
  command: /usr/lib/python2.7/site-packages/graphite/manage.py syncdb --noinput
  args:
    creates: /var/lib/graphite-web/graphite.db
  notify: "restart graphite"

- name: set /var/lib/graphite-web apache:apache
  become: yes
  file:
    path: /var/lib/graphite-web
    owner: apache
    group: apache
    recurse: yes
  notify: "restart graphite"

- name: run handlers
  meta: flush_handlers
