---

- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"

- name: install {{ download }}/{{ file }}
  become: yes
  yum:
    name: "{{ download }}/{{ file }}"
    state: installed
  notify: "restart grafana-server"

- name: setup datasources
  become: yes
  template:
    src: templates/datasources/{{ item }}.yml.j2
    dest: /etc/grafana/provisioning/datasources/{{ item }}.yml
  with_items:
    - graphite
    - elasticsearch
  notify: "restart grafana-server"

- name: setup dashboards
  become: yes
  template:
    src: templates/dashboards/dashboards.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboards.yml
  register: grafana_dashboards_setup

- name: create {{ grafana_dashboards }}
  become: yes
  file:
    path: "{{ grafana_dashboards }}"
    state: directory
    mode: 0755
  notify: "restart grafana-server"

- name: copy dashboards
  become: yes
  copy:
    src: dashboards/{{ item }}.json
    dest: "{{ grafana_dashboards }}/{{ item }}.json"
  with_items:
    - kafka_graphite
    - system_graphite
  notify: "restart grafana-server"

- name: run handlers
  meta: flush_handlers
