---

- name: restart carbon-cache service
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: carbon-cache
    daemon_reload: yes
  listen: "restart graphite"

- name: restart httpd
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: httpd
    daemon_reload: yes
  listen: "restart graphite"
