---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"

- name: extract {{ download }}/{{ file }}
  become: yes
  unarchive:
    src: "{{ download }}/{{ file }}"
    dest: "{{ usr_local }}"
    copy: no
    creates: "{{ kafka_home }}"
    owner: root
    group: root
  notify: "restart kafka"

- name: link to /usr/local/kafka
  become: yes
  file:
    src:  "{{ kafka_home }}"
    dest: /usr/local/kafka
    state: link

- name: set PATH=$PATH:{{ kafka_home }}/bin
  become: yes
  lineinfile:
    dest: "{{ etc_profiles }}/kafka.sh"
    create: yes
    state: present
    regexp: '^PATH'
    line: 'PATH=$PATH:{{ kafka_home }}/bin'

- name: copy server.properties {{ kafka_home }}/config/server.properties
  become: yes
  template:
    src: templates/server.properties.j2
    dest: "{{ kafka_home }}/config/server.properties"
  notify: "restart kafka"

- name: copy kafka.environment {{ kafka_home }}/kafka.environment
  become: yes
  template:
    src: templates/kafka.environment.j2
    dest: "{{ kafka_home }}/kafka.environment"
  notify: "restart kafka"

- name: copy zookeeper_jaas.conf {{ kafka_home }}/config/zookeeper_jaas.conf
  become: yes
  template:
    src: templates/zookeeper_jaas.conf.j2
    dest: "{{ kafka_home }}/config/zookeeper_jaas.conf"
  notify: "restart kafka"

- name: copy jmxtrans-agent.xml {{ jmxtrans_dest }}/{{ jmxagent }}
  become: yes
  template:
    src: templates/jmxtrans-agent.xml.j2
    dest: "{{ jmxtrans_dest }}/{{ jmxagent }}"
  notify: "restart kafka"

- name: create {{ kafka_log_dir }}
  become: yes
  file:
    path: "{{ kafka_log_dir }}"
    state: directory
  notify: "restart kafka"

- name: install kafka systemd unit file
  become: yes
  template:
    src: templates/kafka.service.j2
    dest: "{{ system_units }}/kafka.service"
  notify: "restart kafka"

- name: create {{ exchange }}/client-ssl.properties
  become: yes
  template:
    src: templates/client-ssl.properties.j2
    dest: "{{ ssl_client_dir }}/client-ssl.properties"
  run_once: true

- name: allow cluster communication
  shell: "KAFKA_OPTS=-Djava.security.auth.login.config=/usr/local/kafka/config/zookeeper_jaas.conf kafka-acls.sh --authorizer-properties zookeeper.connect=localhost:2181 --add --operation ClusterAction --cluster --allow-principal User:CN=kafka,OU=org,O=org,L=home,ST=Bavaria,C=DE"
  run_once: true

- name: run handlers
  meta: flush_handlers
