---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"

- name: install {{ download }}/{{ file }}
  become: yes
  yum:
    name: "{{ download }}/{{ file }}"
    state: present
  register: elasticsearch_install

- name: copy elasticsearch.yml to /etc/elasticsearch/elasticsearch.yml
  become: yes
  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  register: elasticsearch_config

- name: restart {{ role_path|basename }}
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: elasticsearch
    daemon_reload: yes
  when: elasticsearch_config.changed or elasticsearch_install.changed
