---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"

- name: extract {{ download }}/{{ file }}
  become: yes
  unarchive:
    src: "{{ download }}/{{ file }}"
    dest: "{{ usr_local }}"
    copy: no
    creates: "{{ prometheus_home }}"

- name: set ownership on {{ prometheus_home }}
  become: yes
  file:
    path: "{{ prometheus_home }}"
    owner: vagrant
    group: vagrant
    recurse: yes
    mode: 0755

- name: copy prometheus.yml to {{ prometheus_home }}/prometheus.yml
  template:
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_home }}/prometheus.yml"
  register: prometheus_config

- name: install prometheus systemd unit file
  become: yes
  template:
    src: templates/prometheus.service.j2
    dest: "{{ system_units }}/prometheus.service"
  register: prometheus_service

- name: restart prometheus
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: prometheus
    daemon_reload: yes
  when: prometheus_service.changed or prometheus_config.changed
