- hosts: elk
  remote_user: vagrant
  serial: 100%
  roles:
  - java8
  - elasticsearch
  - logstash
  - kibana
  - metricbeat

- hosts: prometheus
  remote_user: vagrant
  serial: 100%
  roles:
  - metricbeat
  - prometheus

- hosts: grafana
  remote_user: vagrant
  serial: 100%
  roles:
  - grafana

- hosts: zookeeper
  remote_user: vagrant
  serial: 33%
  roles:
    - java8
    - metricbeat
    - secure
    - zookeeper

- hosts: kafka
  remote_user: vagrant
  serial: 33%
  roles:
    - java8
    - kafka
    - filebeat
