- hosts: all
  remote_user: vagrant
  serial: 100%
  roles:
  - java

- hosts: zookeeper
  remote_user: vagrant
  serial: 33%
  roles:
    - zookeeper

- hosts: kafka
  remote_user: vagrant
  serial: 33%
  roles:
    - kafka
    - metricbeat

- hosts: elk
  remote_user: vagrant
  serial: 100%
  roles:
  - elasticsearch
  - logstash
  - kibana
  - metricbeat

- hosts: grafana
  remote_user: vagrant
  serial: 100%
  roles:
  - graphite
  - grafana
  - metricbeat


- hosts: prometheus
  remote_user: vagrant
  serial: 100%
  roles:
  - metricbeat
  - prometheus
