---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"
    checksum: "{{ checksum }}"

- name: install {{ download }}/{{ file }}
  become: yes
  yum:
    name: "{{ download }}/{{ file }}"
    state: present
  notify: "restart kibana"

- name: copy /etc/kibana/kibana.yml
  become: yes
  template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: "restart kibana"

- name: run handlers
  meta: flush_handlers
