---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"

- name: install {{ download }}/{{ file }}
  become: yes
  yum:
    name: "{{ download }}/{{ file }}"
    state: present
  register: kibana_install

- name: copy /etc/kibana/kibana.yml
  become: yes
  template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  register: kibana_yml

- name: restart {{ role_path|basename }}
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: kibana
    daemon_reload: yes
  when: kibana_install.changed or kibana_yml.changed
