---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"

- name: install {{ download }}/{{ file }}
  become: yes
  yum:
    name: "{{ download }}/{{ file }}"
    state: present
  register: logstash_install

- name: restart {{ role_path|basename }}
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: logstash
    daemon_reload: yes
  when: logstash_install.changed
