---

- import_role:
    name: elastic

- name: install logstash
  become: yes
  yum:
    name: logstash-{{ version }}
    state: present
    update_cache: yes
  notify: "restart logstash"

- name: configure logstash
  become: yes
  template:
    src: templates/logstash.yml.j2
    dest: /etc/logstash/logstash.yml
  notify: "restart logstash"

- name: copy logstash pipelines /etc/logstash/conf.d
  become: yes
  template:
    src: templates/{{ item }}.conf.j2
    dest: /etc/logstash/conf.d/{{ item }}.conf
  with_items:
    - udp
  notify: "restart logstash"
