---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"

- name: install {{ download }}/{{ file }}
  become: yes
  yum:
    name: "{{ download }}/{{ file }}"
    state: present
  register: logstash_install

- name: copy logstash pipelines /etc/logstash/conf.d
  become: yes
  template:
    src: templates/{{ item }}.conf.j2
    dest: /etc/logstash/conf.d/{{ item }}.conf
  with_items:
    - kafka
  register: logstash_pipelines

- name: restart {{ role_path|basename }}
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: logstash
    daemon_reload: yes
  when: logstash_install.changed or logstash_pipelines.changed

- name: wait until logstash http input has been started
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 9000
