---
jdk: "{{ java }}"
file: "jdk-8u172-linux-x64.rpm"
url: http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/{{ file }}
jmx_trans: https://github.com/jmxtrans/jmxtrans-agent/releases/download/jmxtrans-agent-1.2.6/jmxtrans-agent-1.2.6.jar
